import { dateI18n, getSettings } from '@wordpress/date';

const BRAND_DARK = '#1E1B4B';
const BRAND_MID = '#3730A3';
const BRAND_LIGHT = '#EDE9FE';
const TEXT_DARK = '#1E293B';
const TEXT_MUTED = '#64748B';
const PARENT_ROW_FILL = BRAND_LIGHT;
const COL_BORDER = '#E2E8F0';
const AMBER = '#D97706';
const RED = '#DC2626';
const WHITE = '#FFFFFF';

export interface PdfMeta {
	scopeLabel: string;
	totalCount: number;
	lowStockCount: number;
	outOfStockCount: number;
}

export async function generateStockPdf(
	headers: string[],
	rows: ( string | number | null )[][],
	meta: PdfMeta,
	parentRowFlags?: boolean[]
): Promise< void > {
	const [ { jsPDF }, { default: autoTable } ] = await Promise.all( [
		import( 'jspdf' ),
		import( 'jspdf-autotable' ),
	] );

	const orientation = headers.length > 7 ? 'landscape' : 'portrait';
	const doc = new jsPDF( { orientation, unit: 'pt', format: 'a4' } );
	const W = doc.internal.pageSize.getWidth();
	const H = doc.internal.pageSize.getHeight();

	const siteHost = window.location.hostname || 'zexestock';
	const dateStr = dateI18n(
		getSettings().formats.date,
		new Date(),
		undefined
	);

	doc.setFillColor( BRAND_DARK );
	doc.rect( 0, 0, W, 58, 'F' );

	doc.setFontSize( 20 );
	doc.setFont( 'helvetica', 'bold' );
	doc.setTextColor( WHITE );
	doc.text( 'ZEXESTOCK', 32, 34 );

	doc.setFontSize( 10 );
	doc.setFont( 'helvetica', 'normal' );
	doc.setTextColor( '#C4B5FD' );
	doc.text( 'STOCK REPORT', 32, 50 );

	doc.setFontSize( 8.5 );
	doc.setTextColor( '#A5B4FC' );
	doc.text( siteHost, W - 32, 30, { align: 'right' } );
	doc.text( dateStr, W - 32, 45, { align: 'right' } );

	const BOX_W = 210;
	const BOX_H = 54;
	const BOX_X = W - BOX_W - 32;
	const BOX_Y = 66;

	doc.setFillColor( BRAND_LIGHT );
	doc.setDrawColor( BRAND_MID );
	doc.roundedRect( BOX_X, BOX_Y, BOX_W, BOX_H, 4, 4, 'FD' );

	doc.setFontSize( 7 );
	doc.setFont( 'helvetica', 'bold' );
	doc.setTextColor( TEXT_MUTED );
	doc.text( 'REPORT SUMMARY', BOX_X + 8, BOX_Y + 12 );

	const colW = BOX_W / 3;
	const stats = [
		{ label: 'Total', value: String( meta.totalCount ), color: TEXT_DARK },
		{
			label: 'Low Stock',
			value: String( meta.lowStockCount ),
			color: AMBER,
		},
		{
			label: 'Out of Stock',
			value: String( meta.outOfStockCount ),
			color: RED,
		},
	] as const;

	stats.forEach( ( { label, value, color }, i ) => {
		const x = BOX_X + colW * i + 8;
		doc.setFontSize( 8 );
		doc.setFont( 'helvetica', 'normal' );
		doc.setTextColor( color );
		doc.text( label, x, BOX_Y + 28 );
		doc.setFontSize( 14 );
		doc.setFont( 'helvetica', 'bold' );
		doc.text( value, x, BOX_Y + 45 );
	} );

	doc.setFontSize( 8.5 );
	doc.setFont( 'helvetica', 'normal' );
	doc.setTextColor( TEXT_MUTED );
	doc.text( meta.scopeLabel, 32, BOX_Y + 20 );
	doc.setFont( 'helvetica', 'bold' );
	doc.setTextColor( TEXT_DARK );
	doc.text( `${ meta.totalCount } products`, 32, BOX_Y + 38 );

	const tableStartY = BOX_Y + BOX_H + 14;

	const idColIndex = headers.indexOf( 'ID' );
	const typeColIndex = headers.indexOf( 'Type' );
	const saleStartColIndex = headers.indexOf( 'Sale Start' );
	const saleEndColIndex = headers.indexOf( 'Sale End' );
	const columnStyles: Record< number, { cellWidth: number } > = {};
	if ( idColIndex !== -1 ) {
		columnStyles[ idColIndex ] = { cellWidth: 40 };
	}
	if ( typeColIndex !== -1 ) {
		columnStyles[ typeColIndex ] = { cellWidth: 60 };
	}
	if ( saleStartColIndex !== -1 ) {
		columnStyles[ saleStartColIndex ] = { cellWidth: 60 };
	}
	if ( saleEndColIndex !== -1 ) {
		columnStyles[ saleEndColIndex ] = { cellWidth: 60 };
	}

	autoTable( doc, {
		head: [ headers ],
		body: rows.map( ( r ) =>
			r.map( ( c ) =>
				c === null || c === undefined ? '' : String( c )
			)
		),
		startY: tableStartY,
		margin: { top: 32, left: 32, right: 32, bottom: 36 },
		rowPageBreak: 'avoid',
		columnStyles,
		styles: {
			fontSize: 7.5,
			cellPadding: { top: 5, right: 5, bottom: 5, left: 5 },
			textColor: TEXT_DARK,
			lineColor: COL_BORDER,
			lineWidth: 0.4,
			overflow: 'linebreak',
			minCellWidth: 38,
		},
		headStyles: {
			fillColor: BRAND_DARK,
			textColor: WHITE,
			fontStyle: 'bold',
			fontSize: 6,
			cellPadding: { top: 4, right: 3, bottom: 4, left: 3 },
		},
		didParseCell: ( data ) => {
			if (
				data.section === 'body' &&
				parentRowFlags?.[ data.row.index ]
			) {
				data.cell.styles.fillColor = PARENT_ROW_FILL;
			}
		},
	} );

	const totalPages = doc.getNumberOfPages();
	for ( let i = 1; i <= totalPages; i++ ) {
		doc.setPage( i );
		doc.setFontSize( 7.5 );
		doc.setFont( 'helvetica', 'normal' );
		doc.setTextColor( TEXT_MUTED );
		doc.setDrawColor( COL_BORDER );
		doc.line( 32, H - 28, W - 32, H - 28 );
		doc.text( 'Generated by ZexeStock', 32, H - 16 );
		doc.text( `Page ${ i } of ${ totalPages }`, W - 32, H - 16, {
			align: 'right',
		} );
	}

	doc.save( `stock-report-${ new Date().toISOString().slice( 0, 10 ) }.pdf` );
}
